import type { Config } from "tailwindcss";

const color = (name: string) => `rgb(var(--df-${name}) / <alpha-value>)`;

export default {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./lib/**/*.ts", "../../pages/**/*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "cobalt-active": color("primary"),
        "on-tertiary-container": color("on-tertiary-container"),
        "secondary-container": color("secondary-container"),
        "on-primary-fixed": color("on-primary-fixed"),
        error: color("error"),
        "surface-container-low": color("surface-container-low"),
        "on-secondary-fixed": color("on-secondary-fixed"),
        "inverse-primary": color("inverse-primary"),
        "primary-fixed": color("primary-fixed"),
        "inverse-surface": color("inverse-surface"),
        "inverse-on-surface": color("inverse-on-surface"),
        "on-secondary": color("on-secondary"),
        "on-error-container": color("on-error-container"),
        "surface-container-highest": color("surface-container-highest"),
        "tertiary-fixed": color("tertiary-fixed"),
        "surface-bright": color("surface-bright"),
        "surface-dim": color("surface-dim"),
        "on-tertiary": color("on-tertiary"),
        "tertiary-fixed-dim": color("tertiary-fixed-dim"),
        "on-background": color("on-background"),
        "surface-container-lowest": color("surface-container-lowest"),
        "on-secondary-fixed-variant": color("on-secondary-fixed-variant"),
        tertiary: color("tertiary"),
        "outline-variant": color("outline-variant"),
        "surface-container": color("surface-container"),
        "on-tertiary-fixed-variant": color("on-tertiary-fixed-variant"),
        "on-error": color("on-error"),
        surface: color("surface"),
        outline: color("outline"),
        "secondary-fixed": color("secondary-fixed"),
        "on-surface-variant": color("on-surface-variant"),
        "surface-container-high": color("surface-container-high"),
        "error-container": color("error-container"),
        "primary-container": color("primary-container"),
        "on-primary-container": color("on-primary-container"),
        "on-primary": color("on-primary"),
        "secondary-fixed-dim": color("secondary-fixed-dim"),
        "tertiary-container": color("tertiary-container"),
        "on-surface": color("on-surface"),
        primary: color("primary"),
        secondary: color("secondary"),
        "primary-fixed-dim": color("primary-fixed-dim"),
        "on-secondary-container": color("on-secondary-container"),
        "surface-tint": color("surface-tint"),
        background: color("background"),
        "on-primary-fixed-variant": color("on-primary-fixed-variant"),
        "surface-variant": color("surface-variant"),
        "on-tertiary-fixed": color("on-tertiary-fixed"),
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-xxs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        gutter: "var(--df-gutter)",
        "margin-mobile": "1rem",
        "margin-desktop": "2rem",
      },
      fontFamily: {
        "label-sm": ["IBM Plex Sans", "sans-serif"],
        "headline-md": ["IBM Plex Sans", "sans-serif"],
        "body-md": ["IBM Plex Sans", "sans-serif"],
        "headline-lg-mobile": ["IBM Plex Sans", "sans-serif"],
        "headline-lg": ["IBM Plex Sans", "sans-serif"],
        "body-sm": ["IBM Plex Sans", "sans-serif"],
        "label-md": ["IBM Plex Sans", "sans-serif"],
        "headline-sm": ["IBM Plex Sans", "sans-serif"],
        "mono-metric": ["Courier Prime", "monospace"],
        "mono-metric-sm": ["Courier Prime", "monospace"],
        "body-lg": ["IBM Plex Sans", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "mono-metric": ["14px", { lineHeight: "20px", fontWeight: "700" }],
        "mono-metric-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
